# Site settings
title: "Lucas Mucidas"
email: contato@lucasmucidas.com
description: "Analista de negócios, engenheiro e desenvolvedor "
baseurl: ""
url: "http://www.lucasmucidas.com"
title_image: "https://i.imgur.com/9xd8wCR.png"
error_image: "../images/sloth.png"
google_analytics: ""
disqus_account: 
addthis_id:
post_limit: 5

# Social usernames/URLs
twitter_username: lucasmucidas
github_username:  lucasmucidas
instagram_username: lucasmucidas
reddit_username: lucasmucidas
linkedin_username: lucasmucidas

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
